In [ ]:
print('hello')

hello


In [ ]:
!git clone git@github.com:amanzoni1/new_project_deep.git

Cloning into 'new_project_deep'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [ ]:
!git add .
!git commit -m "Your commit message"
!git push

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [5]:
1+1

2

In [6]:
import torch

if torch.cuda.is_available():
    print("Using CUDA (GPU)")
    print(f"Device Name: {torch.cuda.get_device_name(0)}")
else:
    print("Using CPU")

Using CUDA (GPU)
Device Name: Tesla T4


In [8]:
tensor = torch.rand(2, 3, 4)
print("Random Tensor:\n", tensor)

Random Tensor:
 tensor([[[0.7953, 0.9212, 0.9951, 0.3028],
         [0.7644, 0.7438, 0.1255, 0.2763],
         [0.1571, 0.6790, 0.3047, 0.9114]],

        [[0.1285, 0.7268, 0.2279, 0.9076],
         [0.4653, 0.4239, 0.1359, 0.6504],
         [0.5848, 0.9930, 0.6112, 0.7603]]])


In [9]:
tensor.shape

torch.Size([2, 3, 4])

In [10]:
%config Completer.use_jedi = False

In [13]:
def prov():
  print('hello')

In [14]:
prov()

hello


In [17]:
tensor.max()

tensor(0.9951)

In [18]:
a = tensor

In [19]:
a

tensor([[[0.7953, 0.9212, 0.9951, 0.3028],
         [0.7644, 0.7438, 0.1255, 0.2763],
         [0.1571, 0.6790, 0.3047, 0.9114]],

        [[0.1285, 0.7268, 0.2279, 0.9076],
         [0.4653, 0.4239, 0.1359, 0.6504],
         [0.5848, 0.9930, 0.6112, 0.7603]]])

In [20]:
tensor + a

tensor([[[1.5906, 1.8424, 1.9903, 0.6055],
         [1.5289, 1.4876, 0.2510, 0.5526],
         [0.3142, 1.3581, 0.6094, 1.8228]],

        [[0.2570, 1.4536, 0.4557, 1.8153],
         [0.9306, 0.8478, 0.2718, 1.3008],
         [1.1697, 1.9860, 1.2223, 1.5206]]])